### ISSUE TITLE
[BUG] Unable to login with mastodon server whose LOCAL_DOMAIN and WEB_DOMAIN setting are different

### ISSUE THREAD

**Issue by 7sDream** [neodb-social/neodb#100]
**Describe the bug**
Unable to login with mastodon server whose `LOCAL_DOMAIN` and `WEB_DOMAIN` setting are different.

**To Reproduce**
1. go to https://neodb.social/users/login
2. Try to login with my mastodon server, input `mastodon.7sdre.am`.
3. Error reported, with message: "实例连接错误，代码: 404".

**Expected behavior**
Can go to normal login page.

**Additional context**
My instance has `LOCAL_DOMAIN` of `7sdre.am`,  but it's `WEB_DOMAIN` is `mastodon.7sdre.am`, which maybe uncomm but is officially allowed.

Mastodon's official document of
LOCAL_DOMAIN: https://docs.joinmastodon.org/admin/config/#local_domain
WEB_DOMAIN: https://docs.joinmastodon.org/admin/config/#web_domain

I can comfirm my server/nginx was configured correctlly.

I read some source code and find NeoDB use `/api/v1/instance` api to get instance info and use the `uri` field in returned json to continue the login process. The `uri` field's value is `LOCAL_DOMAIN`, which is `7sdre.am`, so the next api call returns 404.

Maybe we can add a checkbox to force use user entered domain?

**Comment by alphatownsman** [comment]
thank you for reporting and digging into this. yes this is a known issue. the fix should be querying the web finger response on WEB_DOMAIN to get the LOCAL_DOMAIN, and store both in db.

let's see if anyone would like to submit a patch, otherwise I'll work on it after finishing off a few things.

**Comment by alphatownsman** [comment]
@7sDream this is merged 

would you help see if https://preview.neodb.social/ fixes your problem before it's pushed to production?

**Comment by 7sDream** [comment]
Sorry for the delay. 

Yes I can confirm the preview (and online) site works for me.
