### ISSUE TITLE
[BUG] API requesting TV show returning internal error

### ISSUE THREAD

**Issue by xmflsct** [neodb-social/neodb#141]
**Describe the bug**
[https://neodb.social/api/tvshow/1puBhCgQGbxl9gFYutBILI/](https://neodb.social/api/tvshow/1puBhCgQGbxl9gFYutBILI/)

**Additional context**
I am the maintainer of [tooot](https://github.com/tooot-app). There are increasing users posting toots with a link to neodb.social, and I think it would be helpful if the app can query such data and display in the app. However when exploring the API, I bump into some internal error linked above, not sure what is happening.

Also, is there a guidance of how to best translate neodb.social web link into API as currently the API requires specifying a type. What I mean is turning https://neodb.social/tv/1puBhCgQGbxl9gFYutBILI into https://neodb.social/api/tvshow/1puBhCgQGbxl9gFYutBILI. Thanks!

**Comment by alphatownsman** [comment]
@xmflsct thanks for reporting this and appreciate your work on the tooot app.

the 500 is now fixed and the endpoint is renamed from /api/tvshow to /api/tv to make things consistent and easier for you.

please be aware the api is still at alpha stage so there might be some upcoming changes with no backward compatibility. however, we'll try to add some documentation to track changes.

**Comment by xmflsct** [comment]
@alphatownsman Thank you! For API data request, shall I add it to https://github.com/neodb-social/neodb/issues/18? For instance it would be great to return the rating data as well as the thumbnail, that will make a preview card pretty complete.

**Comment by xmflsct** [comment]
@alphatownsman awesome!

**Comment by xmflsct** [comment]
![image](https://user-images.githubusercontent.com/292204/224974056-a803973d-fe68-4227-b5b4-e81439f8fdab.jpeg) something like this, tapping on the card will open up the webpage same as tapping on the link itself.
