### ISSUE TITLE
[BUG] API requesting tvseason and album returning status 500

### ISSUE THREAD

**Issue by hikurry** [neodb-social/neodb#148]
**Describe the bug**
tvseason：
https://neodb.social/api/tvseason/51w2qfLjC8r7b9RUiaD3yZ for https://neodb.social/tv/season/51w2qfLjC8r7b9RUiaD3yZ
album：
https://neodb.social/api/album/79GMj8Z75661JjOcqStF9J for https://neodb.social/album/79GMj8Z75661JjOcqStF9J

**Comment by alphatownsman** [comment]
Thanks for the feedback. It's fixed in production.
